In [3]:
!pip install folium

Collecting folium
  Using cached folium-0.11.0-py2.py3-none-any.whl (93 kB)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from folium) (1.18.5)
Collecting branca>=0.3.0
  Using cached branca-0.4.1-py3-none-any.whl (24 kB)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (from folium) (2.24.0)
Requirement already satisfied: jinja2>=2.9 in c:\programdata\anaconda3\lib\site-packages (from folium) (2.11.2)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests->folium) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests->folium) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\programdata\anaconda3\lib\site-packages (from requests->folium) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests->folium) (2.10)
Requirement already satisfied: MarkupSafe>=0.23 in c:\programdata\anaconda3\lib\site-packages (from jinja2>=2.9->folium) (1.1.1)
Installing collected packages: branca, folium
Successfully installed branca-0.4.1 folium-0.11.0

In [4]:
import pandas as pd
import numpy as np
import folium
import matplotlib.pyplot as plt
import matplotlib

matplotlib.rcParams["font.family"]="Malgun Gothic"
matplotlib.rcParams["axes.unicode_minus"]= False

In [9]:
map =folium.Map( location=(37.5012748,127.039625),zoom_start=14 )
mk = folium.Marker( location=(37.5012748,127.039625),popup='test1')
mk.add_to(map)
mk1 = folium.Marker( location=(37.5112748,127.039625),popup='test2')
mk1.add_to(map)
map

In [11]:
df = pd.read_csv('data/도로교통공단_전국_사망교통사고정보(2018).csv',
                encoding='euc-kr')
df

,발생년,발생년월일시,발생분,주야,요일,사망자수,사상자수,중상자수,경상자수,부상신고자수,...,도로형태_대분류,도로형태,가해자_당사자종별_대분류,가해자_당사자종별,피해자_당사자종별_대분류,피해자_당사자종별,발생위치X_UTMK,발생위치Y_UTMK,경도,위도
0,2018,2018021406,35,주,수,1,1,0,0,0,...,단일로,기타단일로,승용차,승용차,보행자,보행자,950497.0,1954702.0,126.939274,37.590388
1,2018,2018090205,23,야,일,1,1,0,0,0,...,교차로,교차로횡단보도내,승용차,승용차,보행자,보행자,953337.0,1950150.0,126.971732,37.549508
2,2018,2018121522,35,야,토,1,1,0,0,0,...,단일로,기타단일로,이륜차,이륜차,없음,없음,956967.0,1954807.0,127.012552,37.591659
3,2018,2018082311,30,주,목,1,1,0,0,0,...,단일로,기타단일로,승합차,승합차,없음,없음,958020.0,1959193.0,127.024227,37.631240
4,2018,2018071600,50,야,월,1,1,0,0,0,...,교차로,교차로횡단보도내,화물차,화물차,보행자,보행자,957606.0,1958258.0,127.019590,37.622794
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3652,2018,2018052103,55,야,월,1,1,0,0,0,...,단일로,기타단일로,승용차,승용차,없음,없음,973070.0,1988564.0,127.193701,37.896529
3653,2018,2018060808,43,주,금,1,1,0,0,0,...,단일로,기타단일로,화물차,화물차,농기계,농기계,979900.0,2006212.0,127.270890,38.055765
3654,2018,2018012010,15,주,토,1,1,0,0,0,...,단일로,기타단일로,승용차,승용차,없음,없음,1001226.0,1959902.0,127.513896,37.638589
3655,2018,2018020321,5,야,토,1,1,0,0,0,...,단일로,기타단일로,승용차,승용차,승용차,승용차,1000491.0,1988419.0,127.505584,37.895621
3656,2018,2018120310,5,주,월,1,2,0,1,0,...,단일로,교량위,승용차,승용차,승용차,승용차,962029.0,2000296.0,127.067505,38.001873

In [ ]:
1. 서울에서 일어난 요일별
사망자수, 사상자수 를 출력하시요
2. 서울 강북구 지역의 교통사고 위치를
지도로 표시하고 각마커에는 법규위반내용
을 표시하시요
3. 부산에서 발생한 총 사망자수를 구하시요
4. 서울지역 월요일에 발생한 사상자수
사고유형 법규위반을 구하시요
5.횡단중 일어난 사고의 요일 
발생지시도, 법규위반, 피해자_당사자종별
을 구하시요

In [17]:
# 1. 서울에서 일어난 요일별 사망자수, 사상자수 를 출력하시요
seoulDF = df[df['발생지시도']=='서울'][['요일','사망자수','사상자수']]
g =seoulDF.groupby('요일')
g.sum().loc[['월','화','수','목','금','토','일']]

    사망자수  사상자수
요일
월     53    84
화     41    45
수     37    48
목     52    76
금     38    52
토     46    62
일     37    58

In [31]:
# 2. 서울 강북구 지역의 교통사고 위치를
# 지도로 표시하고 각마커에는 법규위반내용
# 을 표시하시요
kangbuk =df[ (df['발생지시도']=='서울') & (df['발생지시군구']=='강북구')][['법규위반','위도','경도']]
kangbuk

map =folium.Map( location=(kangbuk['위도'].mean(),kangbuk['경도'].mean()),zoom_start=14 )
for i,s in kangbuk.iterrows():
    mk = folium.Marker( location=(s['위도'],s['경도']),popup=s['법규위반'] )
    mk.add_to(map)
map
map.save('kangbuk.html')

In [35]:
# 3. 부산에서 발생한 총 사망자수를 구하시요
df[df['발생지시도']=='부산']['사망자수'].sum()

123

In [38]:
# 4. 서울지역 월요일에 발생한 사상자수 사고유형 법규위반을 구하시요
df[ (df['발생지시도']=='서울') & (df['요일']=='월')][['사상자수', '사고유형','법규위반']]

      사상자수        사고유형         법규위반
4        1          기타  안전운전 의무 불이행
6        1         횡단중         신호위반
26       1          기타  안전운전 의무 불이행
27       1  길가장자리구역통행중  안전운전 의무 불이행
29       1          기타  보행자 보호의무 위반
424      3        측면충돌  안전운전 의무 불이행
427      1         횡단중         신호위반
430      1         횡단중         신호위반
431      1          기타  안전운전 의무 불이행
437      1         횡단중  보행자 보호의무 위반
443      1       보도통행중  안전운전 의무 불이행
447      2  길가장자리구역통행중  기타(운전자법규위반)
449      1         횡단중  안전운전 의무 불이행
450      1       공작물충돌  안전운전 의무 불이행
531      9          추돌  안전운전 의무 불이행
900      1         횡단중         신호위반
908      1         횡단중         신호위반
915      1         횡단중  안전운전 의무 불이행
919      1  길가장자리구역통행중  안전운전 의무 불이행
924      1          기타  안전운전 의무 불이행
928      1       보도통행중  기타(운전자법규위반)
929      1       차도통행중  안전운전 의무 불이행
1355     4        정면충돌         신호위반
1357     1          기타  안전운전 의무 불이행
1362     1          기타  안전운전 의무 불이행
1784     1        정면충돌       중앙선 침범
1795     3       보도통행중  기타(운전자법규위반)
1800     1         횡단중  안전운전 의무 불이행
1809     2        측면충돌       중앙선 침범
1813     1          기타     안전거리 미확보
2239     1        측면충돌  교차로 통행방법 위반
2240     1          기타  안전운전 의무 불이행
2246     1       공작물충돌  안전운전 의무 불이행
2249     1          기타  안전운전 의무 불이행
2255     1         횡단중       중앙선 침범
2271     1          기타  안전운전 의무 불이행
2713     2        정면충돌         신호위반
2714     1        측면충돌       중앙선 침범
2715     2        정면충돌         신호위반
2725     1          기타  안전운전 의무 불이행
2726     1          기타  안전운전 의무 불이행
2728     2        측면충돌         신호위반
2729     1       차도통행중           과속
2730     1         횡단중  안전운전 의무 불이행
2732     3          기타  안전운전 의무 불이행
2738     1       보도통행중  기타(운전자법규위반)
3163     1       차도통행중  안전운전 의무 불이행
3165     1          기타  안전운전 의무 불이행
3181     1          기타  안전운전 의무 불이행
3189     9        측면충돌         신호위반
3191     1          기타  안전운전 의무 불이행
3200     1         횡단중  안전운전 의무 불이행
3202     2        측면충돌  교차로 통행방법 위반

In [40]:
# 5.횡단중 일어난 사고의 요일 
# 발생지시도, 법규위반, 피해자_당사자종별
# 을 구하시요
df[ df['사고유형']=='횡단중'][['요일', '발생지시도', '법규위반', '피해자_당사자종별']]

     요일 발생지시도         법규위반 피해자_당사자종별
0     수    서울  안전운전 의무 불이행       보행자
1     일    서울  안전운전 의무 불이행       보행자
5     일    서울  안전운전 의무 불이행       보행자
6     월    서울         신호위반       보행자
7     금    서울           과속       보행자
...  ..   ...          ...       ...
3636  목    경기  보행자 보호의무 위반       보행자
3639  금    경기         신호위반       보행자
3643  토    경기  안전운전 의무 불이행       보행자
3646  화    경기  안전운전 의무 불이행       보행자
3647  월    경기  안전운전 의무 불이행       보행자

[791 rows x 4 columns]